"""Key event creation and encoding."""

from __future__ import annotations

import enum
from typing import TYPE_CHECKING

from libghostty._cffi import ffi, lib
from libghostty.vt.errors import GhosttyError, check_result

if TYPE_CHECKING:
    from cffi import FFI

    from libghostty.vt.terminal import Terminal


class KittyKeyFlags(enum.IntFlag):
    """Kitty keyboard protocol flags used by the key encoder."""

    DISABLED = 0x00
    DISAMBIGUATE = 0x01
    REPORT_EVENTS = 0x02
    REPORT_ALTERNATES = 0x04
    REPORT_ALL = 0x08
    REPORT_ASSOCIATED = 0x10
    ALL = 0x1F


class KeyEvent:
    """A keyboard input event."""

    def __init__(self) -> None:
        handle = ffi.new("GhosttyKeyEvent *")
        check_result(lib.ghostty_key_event_new(ffi.NULL, handle))
        self._handle: FFI.CData = handle[0]

    def __del__(self) -> None:
        if hasattr(self, "_handle") and self._handle != ffi.NULL:
            lib.ghostty_key_event_free(self._handle)
            self._handle = ffi.NULL

    @property
    def handle(self) -> FFI.CData:
        return self._handle

    @property
    def action(self) -> int:
        return int(lib.ghostty_key_event_get_action(self._handle))

    @action.setter
    def action(self, value: int) -> None:
        lib.ghostty_key_event_set_action(self._handle, value)

    @property
    def key(self) -> int:
        return int(lib.ghostty_key_event_get_key(self._handle))

    @key.setter
    def key(self, value: int) -> None:
        lib.ghostty_key_event_set_key(self._handle, value)

    @property
    def mods(self) -> int:
        return int(lib.ghostty_key_event_get_mods(self._handle))

    @mods.setter
    def mods(self, value: int) -> None:
        lib.ghostty_key_event_set_mods(self._handle, value)

    @property
    def consumed_mods(self) -> int:
        return int(lib.ghostty_key_event_get_consumed_mods(self._handle))

    @consumed_mods.setter
    def consumed_mods(self, value: int) -> None:
        lib.ghostty_key_event_set_consumed_mods(self._handle, value)

    @property
    def composing(self) -> bool:
        return bool(lib.ghostty_key_event_get_composing(self._handle))

    @composing.setter
    def composing(self, value: bool) -> None:
        lib.ghostty_key_event_set_composing(self._handle, value)

    @property
    def unshifted_codepoint(self) -> int:
        return int(lib.ghostty_key_event_get_unshifted_codepoint(self._handle))

    @unshifted_codepoint.setter
    def unshifted_codepoint(self, value: int) -> None:
        lib.ghostty_key_event_set_unshifted_codepoint(self._handle, value)

    def set_utf8(self, text: str | None) -> None:
        """Set the UTF-8 text generated by this key event.

        The caller must keep the KeyEvent alive while the text is needed.
        """
        if text is None:
            self._utf8_buf = ffi.NULL
            lib.ghostty_key_event_set_utf8(self._handle, ffi.NULL, 0)
            return

        encoded = text.encode("utf-8")
        # Store reference to prevent GC of the buffer
        self._utf8_buf = ffi.new("char[]", encoded)
        lib.ghostty_key_event_set_utf8(self._handle, self._utf8_buf, len(encoded))

    def get_utf8(self) -> str:
        """Return the UTF-8 text stored on this key event."""
        out_len = ffi.new("size_t *")
        buf = lib.ghostty_key_event_get_utf8(self._handle, out_len)
        if buf == ffi.NULL:
            return ""
        return bytes(ffi.buffer(buf, out_len[0])).decode("utf-8")


class KeyEncoder:
    """Encode key events into terminal escape sequences."""

    def __init__(self) -> None:
        handle = ffi.new("GhosttyKeyEncoder *")
        check_result(lib.ghostty_key_encoder_new(ffi.NULL, handle))
        self._handle: FFI.CData = handle[0]

    def __del__(self) -> None:
        if hasattr(self, "_handle") and self._handle != ffi.NULL:
            lib.ghostty_key_encoder_free(self._handle)
            self._handle = ffi.NULL

    def sync_from_terminal(self, terminal: Terminal) -> None:
        """Set encoder options from the terminal's current state."""
        lib.ghostty_key_encoder_setopt_from_terminal(self._handle, terminal.handle)

    def set_kitty_flags(self, flags: KittyKeyFlags) -> None:
        """Set Kitty keyboard protocol flags for subsequent key encoding."""
        value = ffi.new("GhosttyKittyKeyFlags *", int(flags))
        lib.ghostty_key_encoder_setopt(
            self._handle,
            lib.GHOSTTY_KEY_ENCODER_OPT_KITTY_FLAGS,
            value,
        )

    def encode(self, event: KeyEvent, buf_size: int = 128) -> bytes:
        """Encode a key event into an escape sequence.

        Returns:
            The encoded bytes (empty if the event produces no output).
        """
        buf = ffi.new("char[]", buf_size)
        out_len = ffi.new("size_t *")
        result = lib.ghostty_key_encoder_encode(self._handle, event.handle, buf, buf_size, out_len)
        if result == GhosttyError.OUT_OF_SPACE:
            buf = ffi.new("char[]", out_len[0])
            check_result(
                lib.ghostty_key_encoder_encode(self._handle, event.handle, buf, out_len[0], out_len)
            )
        else:
            check_result(result)
        return bytes(ffi.buffer(buf, out_len[0]))
